USE CRM;
GO
CREATE PROCEDURE DBO.DV_GIAYHEN_UPDATE
@MAPB NVARCHAR(10),
@GIAYTO1 NVARCHAR(MAX),
@GIAYTO2 NVARCHAR(MAX),
@GIAYTO3 NVARCHAR(MAX)
AS
IF EXISTS (SELECT 1 FROM DVGIAYHEN WHERE MAPB = @MAPB)
UPDATE DVGIAYHEN SET
GIAYTO1 = @GIAYTO1,
GIAYTO2 = @GIAYTO2,
GIAYTO3 = @GIAYTO3
WHERE MAPB = @MAPB
ELSE
INSERT INTO DVGIAYHEN (MAPB, GIAYTO1,GIAYTO2,GIAYTO3) 
VALUES (@MAPB, @GIAYTO1, @GIAYTO2, @GIAYTO3)