USE [CRM]
GO

/****** Object:  Table [dbo].[DVGIAYHEN]    Script Date: 06/06/2018 16:09:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DVGIAYHEN](
	[MAPB] [nvarchar](10) NOT NULL,
	[GIAYTO1] [nvarchar](max) NULL,
	[GIAYTO2] [nvarchar](max) NULL,
	[GIAYTO3] [nvarchar](max) NULL,
 CONSTRAINT [PK_DVGIAYHEN] PRIMARY KEY CLUSTERED 
(
	[MAPB] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


